### ISSUE TITLE
More modern treesitter grammar available

### ISSUE THREAD

**Issue by olynch** [LionyxML/markdown-ts-mode#1]
I'm not sure if you are aware of this: https://github.com/tree-sitter-grammars/tree-sitter-markdown.

Looks a little complicated because it has top-level and inline parsers, but might be better-maintained.

**Comment by LionyxML** [comment]
Hello there @olynch !

Thanks for pointing that out. I'll take a look into it.

**Comment by LionyxML** [comment]
@olynch 

Refactored the patch to support the more modern Markdown grammar on the commit [4163b63](https://github.com/LionyxML/markdown-ts-mode/commit/4163b632bd8435e029da874292a2dcfe9ab48a53). 

Closing it.

**Comment by olynch** [comment]
Thanks!!
